In [1]:
#Juan Miguel González Hernández
import numpy as np

In [2]:
#Juan Miguel González Hernández
arreglo = np.array([0,1,2,3,4,5,])

In [3]:
#Juan Miguel González Hernández
arreglo, type(arreglo)

(array([0, 1, 2, 3, 4, 5]), numpy.ndarray)

In [34]:
#Juan Miguel González Hernández
notas = [16,17,14,17,19,15]
ar_notas=np.array(notas,dtype=float)

In [35]:
#Juan Miguel González Hernández
ar_notas,type(ar_notas[0])

(array([16., 17., 14., 17., 19., 15.]), numpy.float64)

In [38]:
#Juan Miguel González Hernández

ar_notas_todas=np.array(([0,1,2,3,4,5],notas))
ar_notas_todas

array([[ 0,  1,  2,  3,  4,  5],
       [16, 17, 14, 17, 19, 15]])

In [37]:
#Juan Miguel González Hernández
print(ar_notas_todas.ndim)
print(ar_notas.ndim)

2
1


In [39]:
#Juan Miguel González Hernández
print(ar_notas_todas.shape)
print(ar_notas.shape)

(2, 6)
(6,)


In [41]:
#Juan Miguel González Hernández
arr = np.zeros((2,3),dtype=float)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [43]:
#Juan Miguel González Hernández
ar2 = np.ones((3,4),dtype=float)
print(ar2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [44]:
#Juan Miguel González Hernández
ar4=np.identity((4),dtype=float)
print(ar4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [45]:
#Juan Miguel González Hernández
ar5=np.arange(1,9)
print(ar5)

[1 2 3 4 5 6 7 8]


In [50]:
#Juan Miguel González Hernández
arr = np.arange(1,9)

In [51]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
lista = [1,2,3,4,5,6,7,8]

In [53]:
#Juan Miguel González Hernández
arr.shape = (2,4)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
#Juan Miguel González Hernández
arr + arr

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [58]:
lista+lista

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]

In [59]:
#Juan Miguel González Hernández
arr - arr 

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [60]:
#Juan Miguel González Hernández
arr * arr

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [61]:
#Juan Miguel González Hernández
arr ** arr

array([[       1,        4,       27,      256],
       [    3125,    46656,   823543, 16777216]], dtype=int32)

In [1]:
#Juan Miguel González Hernández
arr / arr

NameError: name 'arr' is not defined

In [2]:
#Juan Miguel González Hernández
import numpy as np

a = np.array([1,2,3],float)
b = np.array([0,1,1],float)

np.dot(b,a)

5.0

In [3]:
a.dot(b)

5.0

In [4]:
#Juan Miguel González Hernández
a = np.array([[5,2],[4,8]],float)
b = np.array([[2,4],[5,3]],float)

print(a, "\n -------------------")
print(b, "\n -------------------")

[[5. 2.]
 [4. 8.]] 
 -------------------
[[2. 4.]
 [5. 3.]] 
 -------------------


In [5]:
#Juan Miguel González Hernández
np.dot(a,b)

array([[20., 26.],
       [48., 40.]])

In [6]:
#Juan Miguel González Hernández
a @ b

array([[20., 26.],
       [48., 40.]])

In [8]:
#Juan Miguel González Hernández
a = np.array([[0,1,4],[5,2,3],[1,4,8]],float)
b = np.array([2,3,5],float)

print(b, "\n -------------------")
print(a, "\n -------------------")

[2. 3. 5.] 
 -------------------
[[0. 1. 4.]
 [5. 2. 3.]
 [1. 4. 8.]] 
 -------------------


In [9]:
#Juan Miguel González Hernández
np.dot(a,b)

array([23., 31., 54.])

In [10]:
#Juan Miguel González Hernández
b @ a

array([20., 28., 57.])

In [11]:
print(np.matmul(a,b))

[23. 31. 54.]


In [12]:
#Juan Miguel González Hernández
a = np.array([[8,5],[3,4]])

print(a, "\n ---------------------------------")

np.linalg.det(a)

[[8 5]
 [3 4]] 
 ---------------------------------


17.0

In [14]:
#Juan Miguel González Hernández

vals,vecs = np.linalg.eig(a)

print(vals, "\n ---------------------------")
print(vecs, "\n ---------------------------")

[10.35889894  1.64110106] 
 ---------------------------
[[ 0.90440309 -0.61810602]
 [ 0.4266791   0.78609474]] 
 ---------------------------


In [15]:
#Juan Miguel González Hernández
a = np.array([2,4,9],float)

In [16]:
a

array([2., 4., 9.])

In [17]:
np.sqrt(a)

array([1.41421356, 2.        , 3.        ])

In [18]:
np.exp(a)

array([7.38905610e+00, 5.45981500e+01, 8.10308393e+03])

In [19]:
np.log(a)

array([0.69314718, 1.38629436, 2.19722458])

In [20]:
np.sin(a)

array([ 0.90929743, -0.7568025 ,  0.41211849])

In [21]:
np.cos(a)

array([-0.41614684, -0.65364362, -0.91113026])

In [22]:
np.mean(a)

5.0

In [23]:
np.std(a)

2.943920288775949

In [24]:
np.var(a)

8.666666666666666