In [1]:
#Juan Miguel González Hernández
import numpy as np

a = np.array(range(64)).reshape((8,8))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [2]:
a[1,1]

9

In [13]:
a[0:7:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [14]:
a[0:7:2,0:4]

array([[ 0,  1,  2,  3],
       [16, 17, 18, 19],
       [32, 33, 34, 35],
       [48, 49, 50, 51]])

In [12]:
a[1,3:]

array([11, 12, 13, 14, 15])

In [17]:
a[1,3:5]

array([11, 12])

In [18]:
a[[1,3,5],[3,6,7]]

array([11, 30, 47])

In [27]:
a[[1,3,5],:3]

array([[ 8,  9, 10],
       [24, 25, 26],
       [40, 41, 42]])

In [31]:
#Juan Miguel González Hernández

data = np.arange(8)
data

array([0, 1, 2, 3, 4, 5, 6, 7])

In [32]:
data < 4

array([ True,  True,  True,  True, False, False, False, False])

In [33]:
data [data<4]

array([0, 1, 2, 3])

In [34]:
data[np.array([True,True,True,True,False,False,False,False])]

array([0, 1, 2, 3])

In [35]:
amigos = np.array(['giulia','victor','joel','andreina','valentina','albert','roque'])

In [36]:
'giulia' in amigos

True

In [37]:
amigos[amigos!='giulia']

array(['victor', 'joel', 'andreina', 'valentina', 'albert', 'roque'],
      dtype='<U9')

In [38]:
amigos[amigos=='giulia']

array(['giulia'], dtype='<U9')