In [7]:
#Juan Miguel González Hernández
import numpy as np

arr_ent = np.random.randint(100, size=(3,4))
arr_ent

array([[38, 96, 90, 27],
       [32, 38,  6, 34],
       [48, 84, 29, 16]])

In [8]:
arr_ent.astype(float)

array([[38., 96., 90., 27.],
       [32., 38.,  6., 34.],
       [48., 84., 29., 16.]])

In [9]:
#Juan Miguel González Hernández
arr_ent

array([[38, 96, 90, 27],
       [32, 38,  6, 34],
       [48, 84, 29, 16]])

In [10]:
arr_ent.sort()
arr_ent

array([[27, 38, 90, 96],
       [ 6, 32, 34, 38],
       [16, 29, 48, 84]])

In [11]:
arr_ent.sort(axis=0)
arr_ent

array([[ 6, 29, 34, 38],
       [16, 32, 48, 84],
       [27, 38, 90, 96]])

In [12]:
#Juan Miguel González Hernández
arr_ent

array([[ 6, 29, 34, 38],
       [16, 32, 48, 84],
       [27, 38, 90, 96]])

In [18]:
arr_ent = arr_ent.reshape(4,3)
arr_ent

array([[ 6, 29, 34],
       [38, 16, 32],
       [48, 84, 27],
       [38, 90, 96]])

In [19]:
plano_arr = arr_ent.flatten()

print(arr_ent)
print(plano_arr)

[[ 6 29 34]
 [38 16 32]
 [48 84 27]
 [38 90 96]]
[ 6 29 34 38 16 32 48 84 27 38 90 96]


In [22]:
lista_arr = plano_arr.tolist()
lista_arr,type(lista_arr)

([6, 29, 34, 38, 16, 32, 48, 84, 27, 38, 90, 96], list)

In [24]:
arrays = np.split(arr_ent,4)
arrays

[array([[ 6, 29, 34]]),
 array([[38, 16, 32]]),
 array([[48, 84, 27]]),
 array([[38, 90, 96]])]

In [28]:
np.concatenate((arrays[1],arrays[0]),axis=1)

array([[38, 16, 32,  6, 29, 34]])

In [30]:
t_arr = arr_ent.T
t_arr

array([[ 6, 38, 48, 38],
       [29, 16, 84, 90],
       [34, 32, 27, 96]])